SRC := src
BIN := bin
CXX := g++
CXXARGS := 
UTILS := $(SRC)/day00/utility.h $(SRC)/day00/utility.cpp
ALL += day01 day02 
# day03 day04
#ALL += day05 day06 day07 day08
#ALL += day09 day10 day11 day12
#ALL += day13 day14 day15 day16
#ALL += day17 day18 day19 day20
#ALL += day21 day22 day23 day24
all: $(ALL)

day01: day01-1 #day01-2
day02: day02-1 #day02-2
day03: day03-1 #day03-2
day04: day04-1 #day04-2
day05: day05-1 #day05-2
day06: day06-1 #day06-2
day07: day07-1 #day07-2
day08: day08-1 #day08-2
day09: day09-1 #day09-2
day10: day10-1 #day10-2
day11: day11-1 #day11-2
day12: day12-1 #day12-2
day13: day13-1 #day13-2
day14: day14-1 #day14-2
day15: day15-1 #day15-2
day16: day16-1 #day16-2
day17: day17-1 #day17-2
day18: day18-1 #day18-2
day19: day19-1 #day19-2
day20: day20-1 #day20-2
day21: day21-1 #day21-2
day22: day22-1 #day22-2
day23: day23-1 #day23-2
day24: day24-1 #day24-2

day01-1:
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day01/day01-1.cpp -o $(BIN)/day01-1
day01-2:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day01/day01-2.cpp -o $(BIN)/day01-2
day02-1:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day02/day02-1.cpp -o $(BIN)/day02-1
day02-2:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day02/day02-2.cpp -o $(BIN)/day02-2
day03-1:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day03/day03-1.cpp -o $(BIN)/day03-1
day03-2:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day03/day03-2.cpp -o $(BIN)/day03-2
day04-1:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day04/day04-1.cpp -o $(BIN)/day04-1
day04-2:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day04/day04-2.cpp -o $(BIN)/day04-2
day05-1:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day05/day05-1.cpp -o $(BIN)/day05-1
day05-2:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day05/day05-2.cpp -o $(BIN)/day05-2
day06-1:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day06/day06-1.cpp -o $(BIN)/day06-1
day06-2:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day06/day06-2.cpp -o $(BIN)/day06-2
day07-1:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day07/day07-1.cpp -o $(BIN)/day07-1
day07-2:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day07/day07-2.cpp -o $(BIN)/day07-2
day08-1:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day08/day08-1.cpp -o $(BIN)/day08-1
day08-2:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day08/day08-2.cpp -o $(BIN)/day08-2
day09-1:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day09/day09-1.cpp -o $(BIN)/day09-1
day09-2:               
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day09/day09-2.cpp -o $(BIN)/day09-2
day10-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day10/day10-1.cpp -o $(BIN)/day10-1
day10-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day10/day10-2.cpp -o $(BIN)/day10-2
day11-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day11/day11-1.cpp -o $(BIN)/day11-1
day11-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day11/day11-2.cpp -o $(BIN)/day11-2
day12-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day12/day12-1.cpp -o $(BIN)/day12-1
day12-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day12/day12-2.cpp -o $(BIN)/day12-2
day13-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day13/day13-1.cpp -o $(BIN)/day13-1
day13-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day13/day13-2.cpp -o $(BIN)/day13-2
day14-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day14/day14-1.cpp -o $(BIN)/day14-1
day14-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day14/day14-2.cpp -o $(BIN)/day14-2
day15-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day15/day15-1.cpp -o $(BIN)/day15-1
day15-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day15/day15-2.cpp -o $(BIN)/day15-2
day16-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day16/day16-1.cpp -o $(BIN)/day16-1
day16-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day16/day16-2.cpp -o $(BIN)/day16-2
day17-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day17/day17-1.cpp -o $(BIN)/day17-1
day17-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day17/day17-2.cpp -o $(BIN)/day17-2
day18-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day18/day18-1.cpp -o $(BIN)/day18-1
day18-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day18/day18-2.cpp -o $(BIN)/day18-2
day19-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day19/day19-1.cpp -o $(BIN)/day19-1
day19-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day19/day19-2.cpp -o $(BIN)/day19-2
day20-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day20/day20-1.cpp -o $(BIN)/day20-1
day20-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day20/day20-2.cpp -o $(BIN)/day20-2
day21-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day21/day21-1.cpp -o $(BIN)/day21-1
day21-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day21/day21-2.cpp -o $(BIN)/day21-2
day22-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day22/day22-1.cpp -o $(BIN)/day22-1
day22-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day22/day22-2.cpp -o $(BIN)/day22-2
day23-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day23/day23-1.cpp -o $(BIN)/day23-1
day23-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day23/day23-2.cpp -o $(BIN)/day23-2
day24-1:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day24/day24-1.cpp -o $(BIN)/day24-1
day24-2:              
	$(CXX) $(CXXARGS) $(UTILS) $(SRC)/day24/day24-2.cpp -o $(BIN)/day24-2
